branches:
  only:
  - master

language: node_js

node_js:
  - stable
  - 12
  - 11
  - node
  - lts/*

install:
  - npm install

script:
  - npm run coverage

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
